/*
================================================================
Create Silver Layer Tables
================================================================
Script Purpose:
    This script creates the tables required for the Silver layer of the 'DataWarehouse' database. 
    Before creating each table, it checks whether the table already exists and drops it if necessary. 
    This ensures that the Silver schema is recreated with a clean structure, ready to store cleansed,
    standardized, and transformed data from the Bronze layer.
    The tables created in this script contain validated and enriched data that has been cleaned, 
    standardized, and prepared for downstream business reporting and analytics. 
    Each table also includes a 'dwh_create_date' column to record when the record was loaded into the
    data warehouse.

Warning:
    Running this script will permanently delete and recreate all existing tables in the Silver schema.
    Any data currently stored in these tables will be lost. 
    Ensure that you have appropriate backups or that the data can be regenerated by reloading and 
    transforming data from the Bronze layer before executing this script.
*/

-- Create 'crm_cust_info' table
IF OBJECT_ID ('silver.crm_cust_info', 'U') IS NOT NULL
	  DROP TABLE silver.crm_cust_info;
CREATE TABLE silver.crm_cust_info(
  	cst_id INT,
  	cst_key	NVARCHAR(50),
  	cst_firstname NVARCHAR(50),
  	cst_lastname NVARCHAR(50),
  	cst_marital_status NVARCHAR(50),
  	cst_gndr NVARCHAR(50),
  	cst_create_date DATE,
    dwh_create_date DATETIME2 DEFAULT GETDATE()
  );

-- Create 'crm_prd_info' table
IF OBJECT_ID ('silver.crm_prd_info', 'U') IS NOT NULL
	  DROP TABLE silver.crm_prd_info;
CREATE TABLE silver.crm_prd_info(
  	prd_id INT,
	  cat_id	NVARCHAR(50),
  	prd_key	NVARCHAR(50),
  	prd_nm	NVARCHAR(50),
  	prd_cost INT,
  	prd_line NVARCHAR(50),
  	prd_start_dt DATE,
  	prd_end_dt DATE,
    dwh_create_date DATETIME2 DEFAULT GETDATE()
);

-- Create 'crm_sales_details' table
IF OBJECT_ID ('silver.crm_sales_details', 'U') IS NOT NULL
	  DROP TABLE silver.crm_sales_details;
CREATE TABLE silver.crm_sales_details(
  	sls_ord_num	NVARCHAR(50),
  	sls_prd_key	NVARCHAR(50),
  	sls_cust_id	INT,
  	sls_order_dt DATE,
  	sls_ship_dt	DATE,
  	sls_due_dt DATE,
  	sls_sales INT,
  	sls_quantity INT,
  	sls_price INT,
    dwh_create_date DATETIME2 DEFAULT GETDATE()
);

-- Create 'erp_CUST_AZ12' table
IF OBJECT_ID ('silver.erp_CUST_AZ12', 'U') IS NOT NULL
	  DROP TABLE silver.erp_CUST_AZ12;
CREATE TABLE silver.erp_CUST_AZ12(
  	cid	NVARCHAR(50),
  	bdate DATE,
  	gen NVARCHAR(50),
    dwh_create_date DATETIME2 DEFAULT GETDATE()
);

-- Create 'erp_LOC_A101' table
IF OBJECT_ID ('silver.erp_LOC_A101', 'U') IS NOT NULL
	  DROP TABLE silver.erp_LOC_A101;
CREATE TABLE silver.erp_LOC_A101(
  	cid	NVARCHAR(50),
  	cntry NVARCHAR(50),
    dwh_create_date DATETIME2 DEFAULT GETDATE()
);

-- Create 'erp_PX_CAT_G1V2' table    
IF OBJECT_ID ('silver.erp_PX_CAT_G1V2', 'U') IS NOT NULL
	  DROP TABLE silver.erp_PX_CAT_G1V2;
CREATE TABLE silver.erp_PX_CAT_G1V2(
  	id NVARCHAR(50),
  	cat NVARCHAR(50),
  	subcat NVARCHAR(50),
  	maintenance NVARCHAR(50),
    dwh_create_date DATETIME2 DEFAULT GETDATE()
);
